GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamF5IiwiaWF0IjoxNzM4NjgxNzM0LCJleHAiOjE3Mzg2ODE3NjR9.4wyQ6Q9bYIiSYzQLiwbvU9QnErFp_Zz_5ODaso0csPA
###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamF5IiwiaWF0IjoxNzM4NjgxNTg2fQ.6ITHuD6xi1ldXiKZHgldVWqvP9vJGCtW0RPAWfqnC2o"
}
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamF5IiwiaWF0IjoxNzM4NjgxNTg2fQ.6ITHuD6xi1ldXiKZHgldVWqvP9vJGCtW0RPAWfqnC2o"
}
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"jay"
}
###
GET http://localhost:5000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTY3NGZjYzkzYWEwYWFlNTQxMzEwMyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczODk2MjIzMiwiZXhwIjoxNzM4OTY1ODMyfQ.9A0ZfCLZPNUB0NVPntoKtKoFCv8H-A7cpRZFvlHK958
###
GET http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTY3NGZjYzkzYWEwYWFlNTQxMzEwMyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczODk2MjIzMiwiZXhwIjoxNzM4OTY1ODMyfQ.9A0ZfCLZPNUB0NVPntoKtKoFCv8H-A7cpRZFvlHK958
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email":"justin@gmail.com",
    "password":"6666",
    "role":"admin"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{ 
    "email":"justin6",
    "password":"6666"
}

###
GET  http://localhost:5000/api/news
###
POST http://localhost:5000/api/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTY3MjRiOTk1M2U5MGVlNTI0ZjI4NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MDg3MjYyNCwiZXhwIjoxNzQwODc2MjI0fQ._etuR1rDaf1Ose50ywF1CE-02cCsxdNVOA11fLTqtps

  {
    "imageUrl": "https://example.com/event2.jpg",
    "name": "Cultural Heritage Showcase",
    "category": "605c72ef153207db2c5e9d3d", 
    "description": "A celebration of diverse cultural traditions with food, music, and art.",
    "date": "2025-07-10T14:00:00Z",
    "location": "Downtown Cultural Center, Detroit, MI"
  }
###
GET  http://localhost:5000/api/events
###
GET  http://localhost:5000/api/speakers
###
GET  http://localhost:5000/api/topics

###
POST http://localhost:5000/api/category
Content-Type: application/json

  {
    "name": "Party",
    "description": "Fun-filled events for socializing, networking, and entertainment."
  }

###
 GET http://localhost:5000/api/category

